# These are personal preferences based on the options listed at
# https://github.com/domluna/JuliaFormatter.jl
# Changing this to a more established style is expected in the future.
always_for_in = true
format_docstrings = true
indent = 4
indent_submodule = true
margin = 80
remove_extra_newlines = true
trailing_comma = false
whitespace_ops_in_indices = true
whitespace_typedefs = true